### ISSUE TITLE
Bump WorldEdit dependency in correspondence with 1.13 update.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena_modules#21]

**Comment by mibby** [comment]
@slipcor Mainly to resolve the WorldEdit module not being able to detect WorldEdit and load.

```
[18:36:05] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/sk89q/worldedit/LocalWorld
[18:36:05] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[18:36:05] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:348)
[18:36:05] [Server thread/WARN]: 	at net.slipcor.pvparena.ncloader.NCBLoader.load(NCBLoader.java:129)
[18:36:05] [Server thread/WARN]: 	at net.slipcor.pvparena.loadables.ArenaModuleManager.<init>(ArenaModuleManager.java:52)
[18:36:05] [Server thread/WARN]: 	at net.slipcor.pvparena.PVPArena.onEnable(PVPArena.java:468)
[18:36:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:36:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[18:36:05] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[18:36:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:438)
[18:36:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:352)
[18:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613)
[18:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575)
[18:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435)
[18:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:311)
[18:36:05] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791)
[18:36:05] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:36:05] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.LocalWorld
[18:36:05] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[18:36:05] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[18:36:05] [Server thread/WARN]: 	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
[18:36:05] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[18:36:05] [Server thread/WARN]: 	... 16 more
[18:36:05] [Server thread/WARN]: [PVP Arena] The JAR file m_worldedit-1.3.4-SNAPSHOT.jar failed to load
```

**Comment by mibby** [comment]
@slipcor To help speed along what is broken, here are the compilation errors and line numbers when trying to compile the WorldEdit module with the dependency for bukkit bumped to 1.13, dependency for PVPArena bumped to 1.13-SNAPSHOT and the dependency for WorldEdit bumped to 7.0.0.

```
    <dependencies>
        <dependency>
            <groupId>org.bukkit</groupId>
            <artifactId>bukkit</artifactId>
            <version>1.13-R0.1-SNAPSHOT</version>
            <type>jar</type>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.slipcor</groupId>
            <artifactId>pvparena</artifactId>
            <version>1.13-SNAPSHOT</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>com.sk89q.worldedit</groupId>
            <artifactId>worldedit-bukkit</artifactId>
            <version>7.0.0-SNAPSHOT</version>
            <type>jar</type>
            <scope>provided</scope>
        </dependency>
    </dependencies>
```

```
-------------------------------------------------------------
COMPILATION ERROR : 
-------------------------------------------------------------
net/slipcor/pvparena/modules/worldedit/PAWE.java:[7,44] error: package com.sk89q.worldedit.bukkit.selections does not exist
net/slipcor/pvparena/modules/worldedit/PAWE.java:[8,44] error: package com.sk89q.worldedit.bukkit.selections does not exist
net/slipcor/pvparena/modules/worldedit/PAWE.java:[9,31] error: package com.sk89q.worldedit.data does not exist
net/slipcor/pvparena/modules/worldedit/PAWE.java:[15,36] error: package com.sk89q.worldedit.schematic does not exist
net/slipcor/pvparena/modules/worldedit/PAWE.java:[17,41] error: cannot find symbol
net/slipcor/pvparena/modules/worldedit/PAWE.java:[199,14] error: cannot find symbol
net/slipcor/pvparena/modules/worldedit/PAWE.java:[199,37] error: cannot find symbol
net/slipcor/pvparena/modules/worldedit/PAWE.java:[259,55] error: cannot find symbol
net/slipcor/pvparena/modules/worldedit/PAWE.java:[260,16] error: cannot find symbol
net/slipcor/pvparena/modules/worldedit/PAWE.java:[260,47] error: cannot find symbol
net/slipcor/pvparena/modules/worldedit/PAWE.java:[336,14] error: cannot find symbol
net/slipcor/pvparena/modules/worldedit/PAWE.java:[336,39] error: cannot find symbol
net/slipcor/pvparena/modules/worldedit/PAWE.java:[349,14] error: cannot find symbol
net/slipcor/pvparena/modules/worldedit/PAWE.java:[349,39] error: cannot find symbol
net/slipcor/pvparena/modules/worldedit/PAWE.java:[357,27] error: package SchematicFormat does not exist
net/slipcor/pvparena/modules/worldedit/PAWE.java:[359,37] error: cannot find symbol
16 errors 
```

**Comment by mibby** [comment]
@slipcor Bump. :(

**Comment by mibby** [comment]
@slipcor WorldEdit module needs to be bumped to WorldEdit 7 beta 4 with its API updated to support the new vector implementation. :(

**Comment by mibby** [comment]
Closing ticket. Has been fixed in a private build via discord. @slipcor Don't forget to push changes live to the repo so it isn't lost forever.
